#!/bin/bash

echo "================================"
echo "VideoFly 积分问题诊断"
echo "================================"
echo ""

echo "🔍 检查步骤："
echo ""
echo "1. 确认当前登录用户"
echo "   - 请查看浏览器右上角显示的邮箱"
echo "   - 记下显示的邮箱地址"
echo ""
echo "2. 在浏览器控制台运行："
echo "   按 F12 -> Console 标签"
echo "   粘贴并运行以下命令："
echo ""
echo "   fetch('/api/v1/credit/balance')"
echo "     .then(r => r.json())"
echo "     .then(data => console.log('积分余额:', data))"
echo ""
echo "3. 查看返回的数据"
echo "   - 如果显示 401 Unauthorized：说明会话有问题"
echo "   - 如果显示 0 积分：说明登录了错误的用户"
echo ""
echo "================================"
echo ""
echo "💡 可能的原因："
echo ""
echo "❓ 原因 1: 登录了不同的用户"
echo "   解决：确认登录的是 demo@visionaryframe.com"
echo ""
echo "❓ 原因 2: Cookie 设置有问题"
echo "   解决：清除所有 Cookie，重新添加"
echo ""
echo "❓ 原因 3: 会话过期"
echo "   解决：重新登录"
echo ""
echo "================================"
echo ""
echo "📝 请告诉我："
echo "1. 浏览器右上角显示的邮箱是什么？"
echo "2. 控制台运行命令后返回什么？"
echo ""
echo "我会根据你的回答帮你解决！"
